# Generated by Django 4.1.5 on 2023-06-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_results_result_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_image',
            new_name='image',
        ),
    ]
