# Generated by Django 4.1.5 on 2023-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_name_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
