# Generated by Django 3.1.5 on 2023-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230628_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alltime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='month_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='week_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_points',
            field=models.IntegerField(default=0),
        ),
    ]
