# Generated by Django 3.1.5 on 2023-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230628_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_day_points',
            field=models.IntegerField(default=0),
        ),
    ]
