# Generated by Django 3.1.5 on 2023-06-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_previous_day_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
