# Generated by Django 3.1.5 on 2023-06-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230629_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
