# Generated by Django 3.1.5 on 2023-06-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230630_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='winner',
            new_name='user',
        ),
    ]
