# Generated by Django 3.1.5 on 2023-06-30 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20230630_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comps', to=settings.AUTH_USER_MODEL),
        ),
    ]
