# Generated by Django 4.1.5 on 2023-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230630_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comp_points',
            field=models.IntegerField(default=0),
        ),
    ]
