# Generated by Django 3.1.5 on 2023-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_profile_comp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Densification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Fiber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='TBB',
            field=models.BooleanField(default=False),
        ),
    ]
