# Generated by Django 3.1.5 on 2022-08-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20220821_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='female',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='male',
        ),
    ]
